development:
    bucket_name: stylfy_development
    access_key_id: 024AWEEZE01KXYDT1PG2
    secret_access_key: VU6E/7mAHS7EVrE3wcRuWYAx5YTCgVBHw0LPcoX5  

test:
    bucket_name: stylfy_test
    access_key_id: 024AWEEZE01KXYDT1PG2
    secret_access_key: VU6E/7mAHS7EVrE3wcRuWYAx5YTCgVBHw0LPcoX5  


production:
    bucket_name: stylfy
    access_key_id: 024AWEEZE01KXYDT1PG2
    secret_access_key: VU6E/7mAHS7EVrE3wcRuWYAx5YTCgVBHw0LPcoX5  




