development:
  adapter: mysql
  database: stylfy_dev
  username: root
  password:
  host: localhost

test:
  adapter: mysql
  database: stylfy_test
  username: root
  password:
  host: localhost
  
production:
    adapter: mysql
    socket: /var/run/mysqld/mysqld.sock
    database: stylfy
    username: stylfy
    password: cl0th1ng
    host: localhost
