development:
    bucket: stylfydev
    access_key_id: 024AWEEZE01KXYDT1PG2
    secret_access_key: VU6E/7mAHS7EVrE3wcRuWYAx5YTCgVBHw0LPcoX5  

test:
    bucket: stylfytest
    access_key_id: 024AWEEZE01KXYDT1PG2
    secret_access_key: VU6E/7mAHS7EVrE3wcRuWYAx5YTCgVBHw0LPcoX5  


production:
    bucket: stylfylive
    access_key_id: 024AWEEZE01KXYDT1PG2
    secret_access_key: VU6E/7mAHS7EVrE3wcRuWYAx5YTCgVBHw0LPcoX5  




